### ISSUE TITLE
caffemodel

### ISSUE THREAD

**Issue by lichen120** [BestJuly/LLCNN#1]
Is it convenient to send caffemodel to lichen120129@163.com

**Comment by BestJuly** [comment]
@lichen120 For this model, I did experiments in Year 2017 in a company. And I did not copy the caffemodel file out. Sorry for that. I think the files provided here are enough and convenient to train and get your model easily. And since the network architecture is simple and I think you can also reproduce this work easily using `pytorch` or `tensorflow`.
